Fix wrongly implemented prefix increment operator overload for GW::Constants::Bag class
gwdevhub/GWCA pull request #11
Opened 2024-09-02 04:16 UTC by zhro

Bag increment is wrongly implemented. The variable is not being incremented at all when used as a prefix increment (postfix was correct). This led to an infinite loop when used in a loop where the variable is expected to increment. The return value was also a copy, not a reference, which is unexpected. A prefix increment is expected to return a reference to the object being incremented, leading to further confusion due to a non-standard implementation.

This change fixes the prefix operator and reuses it when calling the postfix operator, as there is no reason to implement the same method twice.

Here is the old (wrongly) implemented operator demonstrated:

https://ideone.com/kROMPr

And here is the correctly implemented operator demonstrated:

https://ideone.com/wMypay

2024-09-02 17:16 UTC, DubbleClick requested changes
bug

2024-09-02 17:16 UTC, DubbleClick requested changes

2024-09-02 17:16 UTC, DubbleClick commented on Include/GWCA/Constants/Constants.h
> +            return operator++(bag);
this post increment operator will incorrectly return the already incremented value

2024-09-02 17:33 UTC, DubbleClick approved these changes

2024-09-02 17:34 UTC, merged

2024-09-02 17:56 UTC, DubbleClick commented on Include/GWCA/Constants/Constants.h
> +            return operator++(bag);
https://godbolt.org/z/EYrxr51qK

2024-09-02 18:49 UTC, zhro commented
Confirmed. I see that you already fixed it, but here is a validation test. The only difference is that my implementation uses move semantics, but this is a micro-optimization that the compiler will probably due anyways:

https://ideone.com/1Aa0LQ

Thanks for getting this merged.

2024-09-03 04:30 UTC, DubbleClick commented
You should *never* return std::move. It hinders optimisation and explicitly forces the compiler to create the temporary inside the function and move it, instead of just constructing it in place. RVO already guarantees a move over a copy.

Not to mention that moving an enum makes no sense. It doesn't perform dynamic memory allocation, so you couldn't possibly benefit from it.